cpdef seed(unsigned long s)
cpdef double normal_draw(double mu, double sigmasq)
cpdef double chisq_draw(double nu)
cpdef gamma_draw(double a, double b)
cpdef poisson_draw(double mu)
cdef categorical_draw(size_t K, double p[])
cdef dirichlet_draw(size_t K, double alpha[], double theta[])

cdef double logfactorial(unsigned n)
cdef double gammaln(double x)
